server:
  host: 'smtp.exmail.qq.com'
  port: 25

account:
  user: 'no-reply.crspn@idiaoyan.com'
  pass: 'Crspn123'

mail:
  subject: '科普所服务器监控信息'
  from: '科普所监控小机器'
  to:
    - 'yan.zhao@idiaoyan.com'
  cc:
    - 'yan.zhao@idiaoyan.com'

python: /usr/bin/python3

crontab:
  minute: '*/5'  # 0~59
  hour:    # 0~23
  dayofmonth:   # 1~31
  month:   # 1~12
  dayofweek:  # 0~7

monitor:
  cpu:
    interval: 5
    limit: 0.6

  mem:
    limit: 0.5

process:
  - nginx
  - python
  - redis
